### ISSUE TITLE
请赐教您获得这些接口所用到的工具？

### ISSUE THREAD

**Issue by LEORChn** [wazho/hal-automation#1]
我在 inspeckage 中注意到我的测试证书似乎被哈希校验，想知道您是怎么做到的。

**Comment by LEORChn** [comment]
希望能回复一下，感谢 🙏 @wazho

**Comment by wazho** [comment]
@LEORChn 很抱歉現在才回覆你，前陣子工作比較忙碌一點就疏忽了 🙏 

我當時取得這些 API routes 的過程記錄在這裡，你可以參考看看：

https://github.com/liveahero-community/translations/blob/main/doc/TIPS.md

當中有段的 reference video 是很重要的參考資料。
